{{- if .Values.ingress.enabled -}}
{{- $fullName := include "kafka-connect-splunk.fullname" . -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
{{ include "kafka-connect-splunk.labels" . | indent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  tls:
    - hosts:
      - {{ .Values.branch }}.k8s-staging.mmlafleur.com
      secretName: {{ .Values.branch }}-cert
  rules:
    - host: {{ .Values.branch }}.k8s-staging.mmlafleur.com
      http:
        paths:
          - path: /kafka-connect-splunk
            backend:
              serviceName: {{ $fullName }}
              servicePort: http
{{- end }}
