orbs:
  helm: circleci/helm@1.1.2
  slack: circleci/slack@4.4.2
  aws-cli: circleci/aws-cli@2.0.2
  aws-eks: circleci/aws-eks@1.1.0
  aws-ecr: circleci/aws-ecr@7.0.0
  kubernetes: circleci/kubernetes@0.4.0

version: 2.1

parameters:
  mmdb_var:
    type: boolean
    default: false
  placebo_deploy:
    type: boolean
    default: false
  placebo_branch:
    type: string
    default: "master"


jobs:
  production_build:
    docker:
      - image: circleci/python:3.7.1
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - checkout
      - aws-ecr/build-image:
          repo: "${CIRCLE_PROJECT_REPONAME}"
          tag: "${CIRCLE_BRANCH,,}-${CIRCLE_SHA1}"
          dockerfile: "Dockerfile"
          #extra-build-args: '--target staging'
      - aws-cli/install
      - run:
          name: "AWS ECR Login"
          command: |
            aws ecr get-login-password --region $AWS_REGION | docker login -u AWS --password-stdin $AWS_ECR_URL
      - aws-ecr/push-image:
          repo: "${CIRCLE_PROJECT_REPONAME}"
          tag: "${CIRCLE_BRANCH,,}-${CIRCLE_SHA1}"
      - slack/notify:
          event: fail
          template: basic_fail_1
  production_deploy:
    docker:
      - image: circleci/python:3.7.1
    parameters:
      cluster-name:
        type: string
        default: "mmlf-production"
    steps:
      - checkout
      - aws-cli/install
      - kubernetes/install-kubectl
      - helm/install-helm-client:
          version: "v3.5.4"
      - aws-eks/update-kubeconfig-with-authenticator:
          authenticator-release-tag: v0.5.1
          cluster-name: << parameters.cluster-name >>
          aws-region: "${AWS_REGION}"
      - run:
          name: "Helm chart install/upgrade"
          shell: /bin/bash
          command: |
            #helm del --purge ${CIRCLE_BRANCH,,}-${CIRCLE_PROJECT_REPONAME} || :
            helm upgrade --debug --install ${CIRCLE_PROJECT_REPONAME} \
                --namespace shop-wordpress \
                --set branch="${CIRCLE_BRANCH,,}" \
                --set app.environment="${CIRCLE_BRANCH,,}" \
                --set image.tag="${CIRCLE_BRANCH,,}-${CIRCLE_SHA1}" \
                -f ./deploy/production/values.yaml ./deploy/production --recreate-pods
      - slack/notify:
         event: fail
         template: basic_fail_1
  stage_build:
    docker:
      - image: circleci/python:3.7.1
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - checkout
      - run:
          name: "Check if all repositories have the same branch or run placebo build"
          command: |
            for REPO in shop-wordpress react-pdp react-checkout kafka-connect-splunk mmconsumer-client netsuite-connector; do \
                git ls-remote --exit-code --heads git@github.com:mmlafleur/${REPO}.git ${CIRCLE_BRANCH} || \
                  curl -u ${CIRCLECI_API_KEY}: \
                    -X POST --header "Content-Type: application/json" \
                    -d "{ \"branch\":\"master\", \"parameters\": {\"placebo_deploy\":true, \"placebo_branch\":\"${CIRCLE_BRANCH,,}\"}}" \
                    https://circleci.com/api/v2/project/github/mmlafleur/${REPO}/pipeline; \
            done
      - aws-ecr/build-image:
          repo: "staging/${CIRCLE_PROJECT_REPONAME}"
          tag: "${CIRCLE_BRANCH,,}"
          dockerfile: "Dockerfile"
          #extra-build-args: '--target staging'
      - aws-cli/install
      - run:
          name: "AWS ECR Login"
          command: |
            aws ecr get-login-password --region $AWS_REGION | docker login -u AWS --password-stdin $AWS_ECR_URL
      - aws-ecr/push-image:
          repo: "staging/${CIRCLE_PROJECT_REPONAME}"
          tag: "${CIRCLE_BRANCH,,}-${CIRCLE_SHA1}"
      - slack/notify:
          event: fail
          template: basic_fail_1
  stage_deploy:
    docker:
      - image: circleci/python:3.7.1
    steps:
      - checkout
      - aws-cli/install
      - kubernetes/install-kubectl
      - helm/install-helm-client:
          version: "v3.5.4"
      - run:
          name: "Prepare kubectl authentication"
          command: |
            mkdir -p ../.kube
            eval "echo \"$(cat .kube/config.template)\"" > ../.kube/config
      - run:
          name: "Helm chart install/upgrade"
          shell: /bin/bash
          command: |
            helm del --purge ${CIRCLE_BRANCH,,}-${CIRCLE_PROJECT_REPONAME} || :
            helm upgrade --debug --install ${CIRCLE_BRANCH,,}-${CIRCLE_PROJECT_REPONAME} \
                --namespace staging \
                --set branch="${CIRCLE_BRANCH,,}" \
                --set app.environment="${CIRCLE_BRANCH,,}" \
                --set image.tag="${CIRCLE_BRANCH,,}-${CIRCLE_SHA1}" \
                --set image.repository="${AWS_ECR_URL}/staging/${CIRCLE_PROJECT_REPONAME}" \
                -f ./deploy/staging/values.yaml ./deploy/staging
      - slack/notify:
         event: fail
         template: basic_fail_1
  placebo_deployment:
    docker:
      - image: circleci/python:3.7.1
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - checkout
      - aws-ecr/build-image:
          repo: "staging/${CIRCLE_PROJECT_REPONAME}"
          tag: "<< pipeline.parameters.placebo_branch >>"
          dockerfile: "Dockerfile"
      - aws-cli/install
      - run:
          name: "AWS ECR Login"
          command: |
            aws ecr get-login-password --region $AWS_REGION | docker login -u AWS --password-stdin $AWS_ECR_URL
      - aws-ecr/push-image:
          repo: "staging/${CIRCLE_PROJECT_REPONAME}"
          tag: "<< pipeline.parameters.placebo_branch >>"
      - kubernetes/install-kubectl
      - helm/install-helm-client:
          version: "v3.5.4"
      - run:
          name: "Prepare kubectl authentication"
          command: |
            mkdir -p ../.kube
            eval "echo \"$(cat .kube/config.template)\"" > ../.kube/config
      - run:
          name: "Helm chart install/upgrade"
          shell: /bin/bash
          command: |
            helm del --purge << pipeline.parameters.placebo_branch >>-${CIRCLE_PROJECT_REPONAME} || :
            helm upgrade --debug --install << pipeline.parameters.placebo_branch >>-${CIRCLE_PROJECT_REPONAME} \
                --namespace staging \
                --set branch="<< pipeline.parameters.placebo_branch >>" \
                --set image.tag="<< pipeline.parameters.placebo_branch >>" \
                --set image.repository="593202966396.dkr.ecr.us-east-1.amazonaws.com/staging/${CIRCLE_PROJECT_REPONAME}" \
                -f ./deploy/staging/values.yaml ./deploy/staging 
 

workflows:
  version: 2
  placebo_build:
    when: << pipeline.parameters.placebo_deploy >>
    jobs:
      - placebo_deployment:
        parameters:
          placebo_branch: << pipeline.parameters.placebo_branch >>
  circle_build:
    unless: << pipeline.parameters.placebo_deploy >>
    jobs:
      - stage_build:
         context:
          - slack-config
         filters:
           branches:
             ignore:
               - master
               - main
      - stage_deploy:
         context:
          - slack-config
         requires:
           - stage_build
         filters:
           branches:
             ignore:
               - master
               - main
      - production_build:
         context:
          - slack-config
         filters:
           branches:
             only:
               - master
               - main
      - production_deploy:
         context:
          - slack-config
         requires:
           - production_build
         filters:
           branches:
             only:
               - master
               - main

