app:
  environment: staging
replicaCount: 1
image:
  repository: 154821788882.dkr.ecr.us-east-1.amazonaws.com/staging/kafka-connect-splunk
  tag: master
  pullPolicy: Always
branch: ""
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
service:
  type: NodePort
  port: 8083
ingress:
  path: /
  enabled: false
  annotations:
    #kubernetes.io/ingress.class: "nginx"
resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
nodeSelector: {}
tolerations: []
affinity: {}
