apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kafka-connect-splunk.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "kafka-connect-splunk.name" . }}
    helm.sh/chart: {{ include "kafka-connect-splunk.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  strategy:
    rollingUpdate:
      maxUnavailable: {{ .Values.maxUnavailable }}
    type: RollingUpdate
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "kafka-connect-splunk.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      annotations:
        ad.datadoghq.com/{{ .Chart.Name }}.logs: '[{"source":"kafka-connect-splunk","service":"kafka-connect-splunk"}]'
      labels:
        app.kubernetes.io/name: {{ include "kafka-connect-splunk.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args: [ "{{ .Values.image.tag }}" ]
          ports:
            - name: http
              containerPort: 8082
              protocol: TCP
          livenessProbe:
            initialDelaySeconds: 30
            tcpSocket:
              port: http
          readinessProbe:
            initialDelaySeconds: 30
            tcpSocket:
              port: http
          env:
            - name: ENVIRONMENT
              value: {{ .Values.app.environment }}
            - name: X_COMMAND
              value: {{ .Values.image.command }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
